/** @type {import('@wha1echai/dsh-app-check').AppCheckConfig} */
export default {
  name: '@wha1echai/dsh-jobs-app',
  expectedClientInject: [
    '@wha1echai/dsh-webpage',
    '@deepseek-ai/dsh-client-locale',
    '@deepseek-ai/dsh-client-runtime',
    '@deepseek-ai/dsh-client-ui-conversation',
    '@deepseek-ai/dsh-client-ui-primitives',
  ],
  packedAllowlist: [
    'package/package.json',
    'package/README.md',
    'package/LICENSE',
    'package/cordis.patch.yml',
    'package/lib/index.js',
    'package/lib/invariant.js',
    'package/lib/client.js',
    'package/lib/client.js.map',
    'package/lib/types/index.d.ts',
    'package/lib/types/invariant.d.ts',
    'package/lib/types/client/index.d.ts',
    'package/lib/types/client/locales.d.ts',
    'package/lib/types/client/job-view.d.ts',
    'package/lib/types/client/JobFields.d.ts',
    'package/lib/types/client/JobsApp.d.ts',
    'package/lib/types/client/JobsHeaderAction.d.ts',
  ],
  patchMustInclude: ["name: '@wha1echai/dsh-jobs-app'"],
  patchMustNotInclude: ["name: '@wha1echai/dsh-webpage'"],
  allowFileDshPins: false,
  require: {
    publishable: true,
    packageManager: true,
    enginesNode: true,
    clientPlatformWeb: true,
    webpagePeer: true,
    noWorkspaceRanges: true,
    noAdjacentCheckout: true,
    noForbiddenUi: true,
    localeZhEn: true,
    invariantExport: true,
    clientExport: true,
    noNodeDefaultExport: true,
    clientCssInjection: true,
    singleTarball: true,
    noPrepare: true,
  },
}
